#!/usr/bin/env perl
use strict;
use warnings;

my $compressed;

while( defined( $_ = <> ) ) {
    chomp;
    while( $_ ne '') {
        my($next_run_start) = substr($_, 0, 1);
        my($run) = /^([\Q$next_run_start\E]+)/;
        $compressed .= $next_run_start . chr(length($run) + 32);
        $_ = substr($_, length $run);
    }
    $compressed .= "\n";
}
print $compressed;



